### ISSUE TITLE
JSON exception when receiving a report

### ISSUE THREAD

**Issue by aptly-io** [F43nd1r/Acrarium#110]
Hello,

Any idea how to continue from here?

I've acrarium running as a docker container (f43nd1r/acrarium:latest) behind Traefik. https is enabled by Traefik (when disabling https I get a different error on Android than in the main problem: `Caused by: java.io.IOException: Cleartext HTTP traffic to acrarium.xyz not permitted`). On my mobile I see this stack trace:
```
2020-08-26 16:49:14.644 22682-22726/com.example I/ACRA: Sending report /data/user/0/com.example/app_ACRA-approved/2020-08-26T16:36:07.687+02:00.stacktrace
2020-08-26 16:49:14.676 22682-22726/com.example I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2020-08-26 16:49:14.676 22682-22726/com.example I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2020-08-26 16:49:15.022 22682-22726/com.example W/ACRA: Could not send ACRA Post responseCode=500 message=Internal Server Error
2020-08-26 16:49:15.028 22682-22726/com.example E/ACRA: Failed to send crash report for /data/user/0/com.example/app_ACRA-approved/2020-08-26T16:36:07.687+02:00.stacktrace
    org.acra.sender.ReportSenderException: Policy marked this task as incomplete. ACRA will try to send this report again.
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:127)
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:80)
        at org.acra.sender.SendingConductor.sendReports(SendingConductor.java:70)
        at org.acra.sender.JobSenderService.lambda$onStartJob$0$JobSenderService(JobSenderService.java:26)
        at org.acra.sender.-$$Lambda$JobSenderService$MqtyYgRmL36rkxc02MCfjNMMifI.run(Unknown Source:8)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: org.acra.sender.ReportSenderException: Error while sending JSON report via Http POST
        at org.acra.sender.HttpSender.send(HttpSender.java:137)
        at org.acra.sender.ReportSender.send(ReportSender.java:54)
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:115)
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:80) 
        at org.acra.sender.SendingConductor.sendReports(SendingConductor.java:70) 
        at org.acra.sender.JobSenderService.lambda$onStartJob$0$JobSenderService(JobSenderService.java:26) 
        at org.acra.sender.-$$Lambda$JobSenderService$MqtyYgRmL36rkxc02MCfjNMMifI.run(Unknown Source:8) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.io.IOException: Host returned error code 500
        at org.acra.http.BaseHttpRequest.handleResponse(BaseHttpRequest.java:208)
        at org.acra.http.BaseHttpRequest.send(BaseHttpRequest.java:107)
        at org.acra.sender.HttpSender.sendWithoutAttachments(HttpSender.java:166)
        at org.acra.sender.HttpSender.sendHttpRequests(HttpSender.java:148)
        at org.acra.sender.HttpSender.send(HttpSender.java:132)
        at org.acra.sender.ReportSender.send(ReportSender.java:54) 
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:115) 
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:80) 
        at org.acra.sender.SendingConductor.sendReports(SendingConductor.java:70) 
        at org.acra.sender.JobSenderService.lambda$onStartJob$0$JobSenderService(JobSenderService.java:26) 
        at org.acra.sender.-$$Lambda$JobSenderService$MqtyYgRmL36rkxc02MCfjNMMifI.run(Unknown Source:8) 
        at java.lang.Thread.run(Thread.java:919) 
```
while docker logs -f <acrarium-container-id> shows me this:
```
Hibernate: select user0_.`username` as username1_7_, user0_.`mail` as mail2_7_, user0_.`password` as password3_7_, roles1_.`user_username` as user_use1_9_0__, roles1_.`roles` as roles2_9_0__, permission2_.`user_username` as user_use1_8_1__, permission2_.`app_id` as app_id2_8_1__, permission2_.`level` as level3_8_1__ from `user` user0_ left outer join `user_roles` roles1_ on user0_.`username`=roles1_.`user_username` left outer join `user_permissions` permission2_ on user0_.`username`=permission2_.`user_username` where lower(user0_.`username`)=?
Hibernate: select app0_.`id` as id1_0_, app0_.`min_score` as min_scor2_0_, app0_.`name` as name3_0_, app0_.`reporter_username` as reporter4_0_ from `app` app0_ where app0_.`reporter_username`=?
2020-08-26 14:49:10.832 ERROR 1 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.json.JSONException: A JSONObject text must begin with '{' at 2 [character 3 line 1]] with root cause

org.json.JSONException: A JSONObject text must begin with '{' at 2 [character 3 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:507) ~[json-20190722.jar:na]
	at org.json.JSONObject.<init>(JSONObject.java:222) ~[json-20190722.jar:na]
	at org.json.JSONObject.<init>(JSONObject.java:406) ~[json-20190722.jar:na]
	at com.faendir.acra.service.DataService.createNewReport(DataService.kt:271) ~[classes/:0.10.9]
	at com.faendir.acra.service.DataService$$FastClassBySpringCGLIB$$c0f33e7.invoke(<generated>) ~[classes/:0.10.9]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69) ~[spring-security-core-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at com.faendir.acra.service.DataService$$EnhancerBySpringCGLIB$$ae44f873.createNewReport(<generated>) ~[classes/:0.10.9]
	at com.faendir.acra.rest.RestReportInterface.report(RestReportInterface.kt:46) ~[classes/:0.10.9]
	at com.faendir.acra.rest.RestReportInterface$$FastClassBySpringCGLIB$$710fedc2.invoke(<generated>) ~[classes/:0.10.9]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69) ~[spring-security-core-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at com.faendir.acra.rest.RestReportInterface$$EnhancerBySpringCGLIB$$5191a601.report(<generated>) ~[classes/:0.10.9]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665) ~[javax.servlet-api-4.0.1.jar:4.0.1]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:204) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) ~[spring-security-web-5.3.3.RELEASE.jar:5.3.3.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]```

**Comment by F43nd1r** [comment]
What's your acra configuration?

**Comment by aptly-io** [comment]
Might it be the compression that is enabled?

Sorry, it might look a bit messy since I was playing with its many options (I did not use the annotation mechanism):

```
        val builder = CoreConfigurationBuilder(this)
            .setBuildConfigClass(BuildConfig::class.java)
            .setReportFormat(StringFormat.JSON)
//            .setApplicationLogFileDir()
            .setDeleteUnapprovedReportsOnApplicationStart(true)
            .setEnabled(true)
        builder.getPluginConfigurationBuilder(HttpSenderConfigurationBuilder::class.java)
            .setCompress(true)
            .setUri("https://acrarium.xyz/report")                   // Note not the real address
            .setHttpMethod(HttpSender.Method.POST)
            .setBasicAuthLogin("xxxxxxxxxxxxx")              // value from acrarium replaced
            .setBasicAuthPassword("yyyyyyyyyyyy")              // value from acrarium replaced
            .setDropReportsOnTimeout(false)
            .setConnectionTimeout(10_000)
            .setSocketTimeout(1_000)
            .setEnabled(true)
//            // requires Min Sdk-22
//            builder.getPluginConfigurationBuilder(SchedulerConfigurationBuilder::class.java)
//                .setRequiresNetworkType(JobInfo.NETWORK_TYPE_UNMETERED)
//                .setRequiresBatteryNotLow(true)
//                .setEnabled(true)
//                .setRequiresDeviceIdle(true)
//                .setRestartAfterCrash(false)
        builder.getPluginConfigurationBuilder(LimiterConfigurationBuilder::class.java)
            .setDeleteReportsOnAppUpdate(true)
            .setExceptionClassLimit(2) // limit for reports with the same exception class
            .setFailedReportLimit(2) // limit for unsent reports
            .setStacktraceLimit(2) // limit for reports with the same stacktrace
//            .setIgnoredCrashToast(String ignoredCrashToast) // toast shown when a report was not collected or sent because a limit was exceeded
//            .setOverallLimit(int overallLimit) //general limit of reports
//            .setPeriod(long period) // Reports which have been collected before this will not be considered for any limits except AcraLimiter.failedReportLimit()
//            .setPeriodUnit(TimeUnit periodUnit) // Unit of AcraLimiter.period()
//            .setResetLimitsOnAppUpdate(boolean resetLimitsOnAppUpdate) // Resetting limits after an app update allows you to see if a bug still exists.
            .setEnabled(true)
        ACRA.init(this, builder)
```

**Comment by F43nd1r** [comment]
> Might it be the compression that is enabled?

Could be, did you try without?

**Comment by aptly-io** [comment]
I'm very sorry, I cannot try that right now (lost access to letsencrypt's certificate and cannot get a new one right now: "too many certificates already issued for exact set of domains").

**Comment by aptly-io** [comment]
I can confirm that Acrarium behind Traefik is not compatible with 
```
        builder.getPluginConfigurationBuilder(HttpSenderConfigurationBuilder::class.java)
            .setCompress(true)
```
Data arrives when the setting is `false`
