### ISSUE TITLE
Acrarium does not handle a crash report from a signed and obfuscate Android app?

### ISSUE THREAD

**Issue by aptly-io** [F43nd1r/Acrarium#121]
Hello,

I tried using a signed and obfuscated android app.
These are the `build.gradle` settings:
```
        release {
            debuggable true
            jniDebuggable false
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
```
The `ProGuard-rules.pro` is basically empty

I use the Acrarium version: Running version 1.0.0-rc1.

When I force an app crash I see a stack trace in docker logs -f <acrarium-container-id>.
The report did not end up in the Bugs or Report tab.
It seems the compiler with Android Studio 4.0.1 removes or obfuscates parts 
that Acrarium does not handle well? 
Or did I miss configure something on the Android side?
I tried to upload the `./app/build/outputs/mapping/release/mapping.txt` but that does not seem to change anything.

These are the first lines of the Acrarium stack trace.
```
org.json.JSONException: JSONObject["VERSION_NAME"] not found.
	at org.json.JSONObject.get(JSONObject.java:573) ~[json-20190722.jar:na]
	at org.json.JSONObject.getString(JSONObject.java:836) ~[json-20190722.jar:na]
	at com.faendir.acra.service.DataService.getVersion(DataService.kt:294) ~[classes/:1.0.0-rc1]
	at com.faendir.acra.service.DataService.createNewReport(DataService.kt:273) ~[classes/:1.0.0-rc1]
	at com.faendir.acra.service.DataService$$FastClassBySpringCGLIB$$c0f33e7.invoke(<generated>) ~[classes/:1.0.0-rc1]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
```

Thanks

**Comment by F43nd1r** [comment]
Interesting to see that this didn't come up earlier, it is quite basic. As a workaround you can specify your BuildConfig class in ACRA explicitly (recommended for obfuscated apps anyway).

**Comment by aptly-io** [comment]
As suggested, adding a pro-guard rule addresses the issue and now the crash report arrives:

```
-keep class <your.application.package.name>.BuildConfig {
    public <fields>;
}
```
