### ISSUE TITLE
how to set email configurations for sending email

### ISSUE THREAD

**Issue by rezazarchi** [F43nd1r/Acrarium#168]
you mentioned this here 
https://github.com/F43nd1r/Acrarium/wiki/Optional-features#mail-notifications
but where exactly should i put them in docker-compose.yml ?
what should i add if my mail server has ssl/tls ?

**Comment by F43nd1r** [comment]
> but where exactly should i put them in docker-compose.yml ?

Read [the wiki](https://github.com/F43nd1r/Acrarium/wiki/Optional-features#optional-features)

> what should i add if my mail server has ssl/tls ?

You can use any [JavaMail properties](https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html) by prefixing them with `spring.mail.properties.`, e.g. `spring.mail.properties.mail.smtp.ssl.enable=true`

**Comment by rezazarchi** [comment]
i got this error when run docker-compose up:
```services.acrarium.environment.SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE contains true, which is an invalid type, it should be a string, number, or a null
```

**Comment by F43nd1r** [comment]
Use `"true"`

**Comment by rezazarchi** [comment]
now it shows this error when sending email:
```
acrarium    | 2020-11-24 08:53:56.457  WARN 1 --- [         task-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1054, SQLState: 42S22
acrarium    | 2020-11-24 08:53:56.458 ERROR 1 --- [         task-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : Unknown column 'bug' in 'where clause'
acrarium    | 2020-11-24 08:53:56.511 ERROR 1 --- [         task-3] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.faendir.acra.service.MailService.onNewReport(com.faendir.acra.service.NewReportEvent)
acrarium    | 
acrarium    | javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
acrarium    | 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1542) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1581) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at com.querydsl.jpa.impl.AbstractJPAQuery.fetchCount(AbstractJPAQuery.java:82) ~[querydsl-jpa-4.4.0.jar:na]
acrarium    | 	at com.faendir.acra.service.MailService.fetchReportCountOnDay(MailService.kt:106) ~[classes/:1.0.3]
acrarium    | 	at com.faendir.acra.service.MailService.onNewReport(MailService.kt:91) ~[classes/:1.0.3]
acrarium    | 	at com.faendir.acra.service.MailService$$FastClassBySpringCGLIB$$5fd5a53a.invoke(<generated>) ~[classes/:1.0.3]
acrarium    | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.1.jar:5.3.1]
acrarium    | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.3.1.jar:5.3.1]
acrarium    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.1.jar:5.3.1]
acrarium    | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.3.1.jar:5.3.1]
acrarium    | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:371) ~[spring-tx-5.3.1.jar:5.3.1]
acrarium    | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:134) ~[spring-tx-5.3.1.jar:5.3.1]
acrarium    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.1.jar:5.3.1]
acrarium    | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.3.1.jar:5.3.1]
acrarium    | 	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.3.1.jar:5.3.1]
acrarium    | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
acrarium    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
acrarium    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
acrarium    | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
acrarium    | Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
acrarium    | 	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.loader.Loader.getResultSet(Loader.java:2304) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2057) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2019) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.loader.Loader.doQuery(Loader.java:948) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:349) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.loader.Loader.doList(Loader.java:2850) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.loader.Loader.doList(Loader.java:2832) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2664) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.loader.Loader.list(Loader.java:2659) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1414) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1565) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1533) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	... 18 common frames omitted
acrarium    | Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'bug' in 'where clause'
acrarium    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    | 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.4.5.jar:na]
acrarium    | 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar:na]
acrarium    | 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	... 33 common frames omitted
acrarium    | 

```

**Comment by allofmex** [comment]
It also took me some time to get email notifications working, so I would like to share some details (maybe this could also be added to wiki):

This is how the basic configuration may look like

> docker-compose.yml

```
services:
  acrarium:
   environment:
      SPRING_MAIL_HOST: "smtp.yourprovider.com"
      SPRING_MAIL_PORT: "587"
      SPRING_MAIL_PROTOCOL: "smtp"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLED: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLED: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: "true"

      SPRING_MAIL_USERNAME: "your-mail-username"
      SPRING_MAIL_PASSWORD: "your-password"
      SPRING_MAIL_SENDER: "your-email-adress"
```
In acrarium go to your app -> Admin -> Notifications and check the boxes

### For debugging you may also add this:
```
      SPRING_MAIL_PROPERTIES_MAIL_DEBUG: "true"
      SPRING_MAIL_TESTCONNECTION: "true"
```
And start your container via:
```
docker-compose up |grep -i 'smtp'
```

The result should look like:
```
acrarium    | DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
acrarium    | DEBUG SMTP: useEhlo true, useAuth true
acrarium    | DEBUG SMTP: trying to connect to host "smtp.yourprovider.com", port 587, isSSL false
acrarium    | 220 **** (****) Nemesis ESMTP Service ready
acrarium    | DEBUG SMTP: connected to host "smtp.yourprovider.com", port: 587
acrarium    | DEBUG SMTP: Found extension "8BITMIME", arg ""
acrarium    | DEBUG SMTP: Found extension "SIZE", arg "141557760"
acrarium    | DEBUG SMTP: Found extension "STARTTLS", arg ""
acrarium    | DEBUG SMTP: Found extension "8BITMIME", arg ""
acrarium    | DEBUG SMTP: Found extension "AUTH", arg "LOGIN PLAIN"
acrarium    | DEBUG SMTP: Found extension "SIZE", arg "141557760"
acrarium    | DEBUG SMTP: protocolConnect login, host=smtp.yourprovider.com, user=your-mail-username, password=<non-null>
acrarium    | DEBUG SMTP: Attempt to authenticate using mechanisms: LOGIN PLAIN DIGEST-MD5 NTLM XOAUTH2
acrarium    | DEBUG SMTP: Using mechanism LOGIN
acrarium    | DEBUG SMTP: AUTH LOGIN command trace suppressed
acrarium    | DEBUG SMTP: AUTH LOGIN succeeded
```
And a successful mail delivery will end with:
```
acrarium    | DEBUG SMTP: message successfully delivered to mail server
```

#### Notes:
- Use double-quotes arround values (especially at "true")
- For me SSL_ENABLED **and** STARTTLS_ENABLED was needed
- If TESTCONNECTION is set, a test login will be done every time you startup acrarium. Very helpful for debugging since you don't need to create a test bug report
- Be aware that acrarium (v1.6.1) will **only send reports once per bug** (not per report). If you use a self generated bug report to test the mail setup, make sure you delete the last report first!


#### Some other settings I came along:
```
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: "smtp.yourprovider.com"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKETFACTORY_FALLBACK: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_LOCALHOST: "your.domain.com"
      SPRING_MAIL_DEBUG: "true"
```
