### ISSUE TITLE
Error while upping docker-compose

### ISSUE THREAD

**Issue by ravy-amiry** [F43nd1r/Acrarium#188]
Upping this exact `docker-compose`:

```
version: "3.7"

services:
   database:
       image: mysql
       container_name: database    
       environment:
           MYSQL_ROOT_PASSWORD: root_password
           MYSQL_DATABASE: acrarium
           MYSQL_USER: acrarium
           MYSQL_PASSWORD: secure_password
       expose:
        - "3306"
       volumes:
        - acrarium_data:/var/lib/mysql
   acrarium:
       image: f43nd1r/acrarium:latest
       container_name: acrarium
       depends_on:
        - database
       ports:
        - 8080:8080
       environment:
           SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/acrarium?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
           SPRING_DATASOURCE_USERNAME: acrarium
           SPRING_DATASOURCE_PASSWORD: secure_password
           SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL57Dialect
     
volumes:
   acrarium_data:
```
Causes this error:

```acrarium    | 2021-01-08 12:19:38.237  INFO 1 --- [           main] com.faendir.acra.BackendApplicationKt    : Starting BackendApplicationKt v1.1.0 using Java 11.0.9.1 on 83a102ed264b with PID 1 (/application/BOOT-INF/classes started by root in /application)
acrarium    | 2021-01-08 12:19:38.240  INFO 1 --- [           main] com.faendir.acra.BackendApplicationKt    : No active profile set, falling back to default profiles: default
acrarium    | 2021-01-08 12:19:38.386  INFO 1 --- [           main] o.s.c.a.ConfigurationClassParser         : Properties location [file:${user.home}/.config/acrarium/application.properties] not resolvable: /root/.config/acrarium/application.properties (No such file or directory)
acrarium    | 2021-01-08 12:19:38.387  INFO 1 --- [           main] o.s.c.a.ConfigurationClassParser         : Properties location [file:${user.home}/.acra/application.properties] not resolvable: /root/.acra/application.properties (No such file or directory)
acrarium    | 2021-01-08 12:19:39.831  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
acrarium    | 2021-01-08 12:19:39.894  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 57 ms. Found 0 JPA repository interfaces.
acrarium    | 2021-01-08 12:19:40.206  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@539316bb' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
acrarium    | 2021-01-08 12:19:40.213  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
acrarium    | 2021-01-08 12:19:40.466  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
acrarium    | 2021-01-08 12:19:40.511  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
acrarium    | 2021-01-08 12:19:40.512  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.41]
acrarium    | 2021-01-08 12:19:40.681  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
acrarium    | 2021-01-08 12:19:40.681  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2374 ms
acrarium    | 2021-01-08 12:19:41.071  INFO 1 --- [           main] c.v.f.s.VaadinServletContextInitializer  : Search for VaadinAppShell took 93 ms
acrarium    | 2021-01-08 12:19:41.214  INFO 1 --- [           main] c.g.z.f.compression.CompressingFilter    : CompressingFilter has initialized
acrarium    | 2021-01-08 12:19:41.345  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
acrarium    | 2021-01-08 12:19:42.683 ERROR 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.
acrarium    | 
acrarium    | java.sql.SQLException: Access denied for user 'acrarium'@'172.21.0.3' (using password: YES)
acrarium    |   at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    |   at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    |   at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    |   at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    |   at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    |   at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    |   at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    |   at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-3.4.5.jar:na]
acrarium    |   at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[HikariCP-3.4.5.jar:na]
acrarium    |   at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-3.4.5.jar:na]
acrarium    |   at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[HikariCP-3.4.5.jar:na]
acrarium    |   at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[HikariCP-3.4.5.jar:na]
acrarium    |   at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-3.4.5.jar:na]
acrarium    |   at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-3.4.5.jar:na]
acrarium    |   at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:313) ~[liquibase-core-3.10.3.jar:na]
acrarium    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1847) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1159) ~[spring-context-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:913) ~[spring-context-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.1.jar:2.4.1]
acrarium    |   at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.1.jar:2.4.1]
acrarium    |   at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.1.jar:2.4.1]
acrarium    |   at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.1.jar:2.4.1]
acrarium    |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.1.jar:2.4.1]
acrarium    |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-2.4.1.jar:2.4.1]
acrarium    |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-2.4.1.jar:2.4.1]
acrarium    |   at com.faendir.acra.BackendApplicationKt.main(BackendApplication.kt:43) ~[classes/:1.1.0]
acrarium    |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
acrarium    |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
acrarium    |   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
acrarium    |   at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
acrarium    |   at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[application/:na]
acrarium    |   at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[application/:na]
acrarium    |   at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[application/:na]
acrarium    |   at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[application/:na]
acrarium    | 
acrarium    | 2021-01-08 12:19:42.686  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in file [/application/BOOT-INF/classes/com/faendir/acra/liquibase/ChangeAwareSpringLiquibase.class]: Invocation of init method failed; nested exception is liquibase.exception.DatabaseException: java.sql.SQLException: Access denied for user 'acrarium'@'172.21.0.3' (using password: YES)
acrarium    | 2021-01-08 12:19:42.696  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
acrarium    | 2021-01-08 12:19:42.700  INFO 1 --- [           main] c.g.z.f.compression.CompressingFilter    : CompressingFilter is being destroyed...
acrarium    | 2021-01-08 12:19:42.734  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 
acrarium    | 
acrarium    | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
acrarium    | 2021-01-08 12:19:42.755 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
acrarium    | 
acrarium    | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in file [/application/BOOT-INF/classes/com/faendir/acra/liquibase/ChangeAwareSpringLiquibase.class]: Invocation of init method failed; nested exception is liquibase.exception.DatabaseException: java.sql.SQLException: Access denied for user 'acrarium'@'172.21.0.3' (using password: YES)
acrarium    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1159) ~[spring-context-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:913) ~[spring-context-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.1.jar:2.4.1]
acrarium    |   at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.1.jar:2.4.1]
acrarium    |   at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.1.jar:2.4.1]
acrarium    |   at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.1.jar:2.4.1]
acrarium    |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.1.jar:2.4.1]
acrarium    |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-2.4.1.jar:2.4.1]
acrarium    |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-2.4.1.jar:2.4.1]
acrarium    |   at com.faendir.acra.BackendApplicationKt.main(BackendApplication.kt:43) ~[classes/:1.1.0]
acrarium    |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
acrarium    |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
acrarium    |   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
acrarium    |   at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
acrarium    |   at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[application/:na]
acrarium    |   at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[application/:na]
acrarium    |   at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[application/:na]
acrarium    |   at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[application/:na]
acrarium    | Caused by: liquibase.exception.DatabaseException: java.sql.SQLException: Access denied for user 'acrarium'@'172.21.0.3' (using password: YES)
acrarium    |   at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:318) ~[liquibase-core-3.10.3.jar:na]
acrarium    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1847) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784) ~[spring-beans-5.3.2.jar:5.3.2]
acrarium    |   ... 27 common frames omitted
acrarium    | Caused by: java.sql.SQLException: Access denied for user 'acrarium'@'172.21.0.3' (using password: YES)
acrarium    |   at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    |   at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    |   at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    |   at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    |   at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    |   at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    |   at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.22.jar:8.0.22]
acrarium    |   at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-3.4.5.jar:na]
acrarium    |   at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[HikariCP-3.4.5.jar:na]
acrarium    |   at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-3.4.5.jar:na]
acrarium    |   at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[HikariCP-3.4.5.jar:na]
acrarium    |   at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[HikariCP-3.4.5.jar:na]
acrarium    |   at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-3.4.5.jar:na]
acrarium    |   at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-3.4.5.jar:na]
acrarium    |   at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:313) ~[liquibase-core-3.10.3.jar:na]
acrarium    |   ... 29 common frames omitted
acrarium    | 
acrarium exited with code 1
```

NOTE: the database creation section committed, because it's successful.

**Comment by F43nd1r** [comment]
I've reworked the [recommended docker-compose.yml](https://github.com/F43nd1r/Acrarium/wiki/Setup-guide#2-create-compose-file) to fix several issues, likely to include this error (I wasn't able to recreate this exact messsage).
Please note that you'll need to delete existing docker volumes for the changes to have an effect. The acrarium container may also fail several times while the database container is still in initial setup.

**Comment by ravy-amiry** [comment]
Thanks to the quick reply. OK. I just replaced the last line in your new `docker-compose.yaml` file:

`SPRING_JPA_DATABASEPLATFORM: org.hibernate.dialect.MySQL57Dialect
`

with this line:

`SPRING_DATASOURCE_PLATFORM: org.hibernate.dialect.MySQL57Dialect
`

And it started like a charm. You may want to update the compose file. Thank you again.

**Comment by F43nd1r** [comment]
> with this line: SPRING_DATASOURCE_PLATFORM: org.hibernate.dialect.MySQL57Dialect 

This means jpa will try to autodetect your database, works in most cases.

> NOTE: Shouldn't you remove - from environment's parameters? I mean SPRING_JPA_DATABASE-PLATFORM shouldn't be SPRING_JPA_DATABASEPLATFORM?

Yes, my bad.

> Isn't it better to use - instead of "" in environment parameters?

The result is the same, use the style you prefer.

> Also, would you consider to switch to PostgreSQL?

I use mysql with no intention to switch, so that is what I develop for. Acrarium should be mostly compatible with other databases, but there was a hibernate bug which prevented it from working with most stricter databases.
