### ISSUE TITLE
Get java.lang.IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by falahatiali** [F43nd1r/Acrarium#198]
I have many apps in my apps list. when I want click one of them I face following error. I can paste here all messages 
```
2021-01-26 07:18:44.624 ERROR 1 --- [nio-8080-exec-7] c.v.flow.server.DefaultErrorHandler      : 

java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[na:na]

```

**Comment by falahatiali** [comment]
when I click on my app name I get this error 

```
Internal error
Please notify the administrator.
Take note of any unsaved data, and click here or press ESC to continue.
```
when I try to read its log I face this error :

```
Hibernate: select app0_.`id` as id1_0_, app0_.`min_score` as min_scor2_0_, app0_.`name` as name3_0_, app0_.`reporter_username` as reporter4_0_ from `app` app0_ where app0_.`id`=?
Hibernate: select user0_.`username` as username1_7_0_, user0_.`mail` as mail2_7_0_, user0_.`password` as password3_7_0_, permission1_.`user_username` as user_use1_8_1_, permission1_.`app_id` as app_id2_8_1_, permission1_.`level` as level3_8_1_, app2_.`id` as id1_0_2_, app2_.`min_score` as min_scor2_0_2_, app2_.`name` as name3_0_2_, app2_.`reporter_username` as reporter4_0_2_, roles3_.`user_username` as user_use1_9_3_, roles3_.`roles` as roles2_9_3_ from `user` user0_ left outer join `user_permissions` permission1_ on user0_.`username`=permission1_.`user_username` left outer join `app` app2_ on permission1_.`app_id`=app2_.`id` left outer join `user_roles` roles3_ on user0_.`username`=roles3_.`user_username` where user0_.`username`=?
Hibernate: select version0_.`id` as id1_10_, version0_.`app_id` as app_id5_10_, version0_.`code` as code2_10_, version0_.`name` as name4_10_ from `version` version0_ where version0_.`app_id`=?
Hibernate: select app0_.`id` as id1_0_0_, app0_.`min_score` as min_scor2_0_0_, app0_.`name` as name3_0_0_, app0_.`reporter_username` as reporter4_0_0_ from `app` app0_ where app0_.`id`=?
Hibernate: select user0_.`username` as username1_7_0_, user0_.`mail` as mail2_7_0_, user0_.`password` as password3_7_0_, permission1_.`user_username` as user_use1_8_1_, permission1_.`app_id` as app_id2_8_1_, permission1_.`level` as level3_8_1_, app2_.`id` as id1_0_2_, app2_.`min_score` as min_scor2_0_2_, app2_.`name` as name3_0_2_, app2_.`reporter_username` as reporter4_0_2_, roles3_.`user_username` as user_use1_9_3_, roles3_.`roles` as roles2_9_3_ from `user` user0_ left outer join `user_permissions` permission1_ on user0_.`username`=permission1_.`user_username` left outer join `app` app2_ on permission1_.`app_id`=app2_.`id` left outer join `user_roles` roles3_ on user0_.`username`=roles3_.`user_username` where user0_.`username`=?
Hibernate: select count(distinct bug0_.`id`) as col_0_0_ from `bug` bug0_ left outer join `stacktrace` stacktrace1_ on (stacktrace1_.`bug_id`=bug0_.`id`) left outer join `report` report2_ on (report2_.`stacktrace_id`=stacktrace1_.`id`) left outer join `version` version3_ on bug0_.`solved_version`=version3_.`id` where bug0_.`app_id`=? and (bug0_.`solved_version` is null)
Hibernate: select bug0_.`id` as col_0_0_, max(report2_.`date`) as col_1_0_, count(report2_.`id`) as col_2_0_, max(version4_.`code`) as col_3_0_, count(distinct report2_.`installation_id`) as col_4_0_, version3_.`id` as id1_10_3_, bug0_.`id` as id1_2_0_, version3_.`id` as id1_10_1_, bug0_.`app_id` as app_id3_2_0_, bug0_.`solved_version` as solved_v4_2_0_, bug0_.`title` as title2_2_0_, version3_.`app_id` as app_id5_10_1_, version3_.`code` as code2_10_1_, version3_.`name` as name4_10_1_ from `bug` bug0_ left outer join `stacktrace` stacktrace1_ on (stacktrace1_.`bug_id`=bug0_.`id`) left outer join `report` report2_ on (report2_.`stacktrace_id`=stacktrace1_.`id`) left outer join `version` version3_ on bug0_.`solved_version`=version3_.`id` cross join `version` version4_ where stacktrace1_.`version_id`=version4_.`id` and bug0_.`app_id`=? and (bug0_.`solved_version` is null) group by bug0_.`id` order by max(report2_.`date`) desc limit ?
Hibernate: select app0_.`id` as id1_0_0_, app0_.`min_score` as min_scor2_0_0_, app0_.`name` as name3_0_0_, app0_.`reporter_username` as reporter4_0_0_ from `app` app0_ where app0_.`id`=?
Hibernate: select user0_.`username` as username1_7_0_, user0_.`mail` as mail2_7_0_, user0_.`password` as password3_7_0_, permission1_.`user_username` as user_use1_8_1_, permission1_.`app_id` as app_id2_8_1_, permission1_.`level` as level3_8_1_, app2_.`id` as id1_0_2_, app2_.`min_score` as min_scor2_0_2_, app2_.`name` as name3_0_2_, app2_.`reporter_username` as reporter4_0_2_, roles3_.`user_username` as user_use1_9_3_, roles3_.`roles` as roles2_9_3_ from `user` user0_ left outer join `user_permissions` permission1_ on user0_.`username`=permission1_.`user_username` left outer join `app` app2_ on permission1_.`app_id`=app2_.`id` left outer join `user_roles` roles3_ on user0_.`username`=roles3_.`user_username` where user0_.`username`=?
2021-01-27 03:59:58.828 ERROR 1 --- [nio-8080-exec-1] c.v.flow.server.DefaultErrorHandler      : 

com.querydsl.core.types.ExpressionException: null
	at com.querydsl.core.types.ConstructorExpression.newInstance(ConstructorExpression.java:149) ~[querydsl-core-4.4.0.jar:na]
	at com.querydsl.core.support.NumberConversions.newInstance(NumberConversions.java:86) ~[querydsl-core-4.4.0.jar:na]

```

**Comment by F43nd1r** [comment]
post the full stacktrace
