### ISSUE TITLE
Delete Version Resulted in Internal Error

### ISSUE THREAD

**Issue by Kasina09** [F43nd1r/Acrarium#217]
Version 0 suddenly appeared in Admin tab and I deleted it. But after that, I cannot access the application inside Acrarium (only the application which version 0 was deleted).
It said:
`Internal error
Please notify the administrator.
Take note of any unsaved data, and click here or press ESC to continue.`

The error is the same with issue #198 but I don't see the solution there...

Here's the full log:
```
acrarium    | Hibernate: select app0_.`id` as id1_0_, app0_.`min_score` as min_scor2_0_, app0_.`name` as name3_0_, app0_.`reporter_username` as reporter4_0_ from `app` app0_ where app0_.`id`=?
acrarium    | Hibernate: select user0_.`username` as username1_7_0_, user0_.`mail` as mail2_7_0_, user0_.`password` as password3_7_0_, permission1_.`user_username` as user_use1_8_1_, permission1_.`app_id` as app_id2_8_1_, permission1_.`level` as level3_8_1_, app2_.`id` as id1_0_2_, app2_.`min_score` as min_scor2_0_2_, app2_.`name` as name3_0_2_, app2_.`reporter_username` as reporter4_0_2_, roles3_.`user_username` as user_use1_9_3_, roles3_.`roles` as roles2_9_3_ from `user` user0_ left outer join `user_permissions` permission1_ on user0_.`username`=permission1_.`user_username` left outer join `app` app2_ on permission1_.`app_id`=app2_.`id` left outer join `user_roles` roles3_ on user0_.`username`=roles3_.`user_username` where user0_.`username`=?
acrarium    | Hibernate: select app0_.`id` as id1_0_, app0_.`min_score` as min_scor2_0_, app0_.`name` as name3_0_, app0_.`reporter_username` as reporter4_0_ from `app` app0_ where app0_.`id`=?
acrarium    | Hibernate: select user0_.`username` as username1_7_0_, user0_.`mail` as mail2_7_0_, user0_.`password` as password3_7_0_, permission1_.`user_username` as user_use1_8_1_, permission1_.`app_id` as app_id2_8_1_, permission1_.`level` as level3_8_1_, app2_.`id` as id1_0_2_, app2_.`min_score` as min_scor2_0_2_, app2_.`name` as name3_0_2_, app2_.`reporter_username` as reporter4_0_2_, roles3_.`user_username` as user_use1_9_3_, roles3_.`roles` as roles2_9_3_ from `user` user0_ left outer join `user_permissions` permission1_ on user0_.`username`=permission1_.`user_username` left outer join `app` app2_ on permission1_.`app_id`=app2_.`id` left outer join `user_roles` roles3_ on user0_.`username`=roles3_.`user_username` where user0_.`username`=?
acrarium    | Hibernate: select version0_.`id` as id1_10_, version0_.`app_id` as app_id5_10_, version0_.`code` as code2_10_, version0_.`name` as name4_10_ from `version` version0_ where version0_.`app_id`=?
acrarium    | Hibernate: select app0_.`id` as id1_0_0_, app0_.`min_score` as min_scor2_0_0_, app0_.`name` as name3_0_0_, app0_.`reporter_username` as reporter4_0_0_ from `app` app0_ where app0_.`id`=?
acrarium    | Hibernate: select user0_.`username` as username1_7_0_, user0_.`mail` as mail2_7_0_, user0_.`password` as password3_7_0_, permission1_.`user_username` as user_use1_8_1_, permission1_.`app_id` as app_id2_8_1_, permission1_.`level` as level3_8_1_, app2_.`id` as id1_0_2_, app2_.`min_score` as min_scor2_0_2_, app2_.`name` as name3_0_2_, app2_.`reporter_username` as reporter4_0_2_, roles3_.`user_username` as user_use1_9_3_, roles3_.`roles` as roles2_9_3_ from `user` user0_ left outer join `user_permissions` permission1_ on user0_.`username`=permission1_.`user_username` left outer join `app` app2_ on permission1_.`app_id`=app2_.`id` left outer join `user_roles` roles3_ on user0_.`username`=roles3_.`user_username` where user0_.`username`=?
acrarium    | 2021-03-09 04:39:43.641  WARN 1 --- [nio-8080-exec-4] c.v.f.s.c.r.AbstractRpcInvocationHandler : Got an RPC for non-existent node: 245
acrarium    | 2021-03-09 04:39:43.641  WARN 1 --- [nio-8080-exec-4] c.v.f.s.c.r.AbstractRpcInvocationHandler : Got an RPC for non-existent node: 245
acrarium    | Hibernate: select count(distinct bug0_.`id`) as col_0_0_ from `bug` bug0_ left outer join `stacktrace` stacktrace1_ on (stacktrace1_.`bug_id`=bug0_.`id`) left outer join `report` report2_ on (report2_.`stacktrace_id`=stacktrace1_.`id`) left outer join `version` version3_ on bug0_.`solved_version`=version3_.`id` where bug0_.`app_id`=? and (bug0_.`solved_version` is null)
acrarium    | Hibernate: select bug0_.`id` as col_0_0_, max(report2_.`date`) as col_1_0_, count(report2_.`id`) as col_2_0_, max(version4_.`code`) as col_3_0_, count(distinct report2_.`installation_id`) as col_4_0_, version3_.`id` as id1_10_3_, bug0_.`id` as id1_2_0_, version3_.`id` as id1_10_1_, bug0_.`app_id` as app_id3_2_0_, bug0_.`solved_version` as solved_v4_2_0_, bug0_.`title` as title2_2_0_, version3_.`app_id` as app_id5_10_1_, version3_.`code` as code2_10_1_, version3_.`name` as name4_10_1_ from `bug` bug0_ left outer join `stacktrace` stacktrace1_ on (stacktrace1_.`bug_id`=bug0_.`id`) left outer join `report` report2_ on (report2_.`stacktrace_id`=stacktrace1_.`id`) left outer join `version` version3_ on bug0_.`solved_version`=version3_.`id` cross join `version` version4_ where stacktrace1_.`version_id`=version4_.`id` and bug0_.`app_id`=? and (bug0_.`solved_version` is null) group by bug0_.`id` order by max(report2_.`date`) desc limit ?
acrarium    | Hibernate: select app0_.`id` as id1_0_0_, app0_.`min_score` as min_scor2_0_0_, app0_.`name` as name3_0_0_, app0_.`reporter_username` as reporter4_0_0_ from `app` app0_ where app0_.`id`=?
acrarium    | Hibernate: select user0_.`username` as username1_7_0_, user0_.`mail` as mail2_7_0_, user0_.`password` as password3_7_0_, permission1_.`user_username` as user_use1_8_1_, permission1_.`app_id` as app_id2_8_1_, permission1_.`level` as level3_8_1_, app2_.`id` as id1_0_2_, app2_.`min_score` as min_scor2_0_2_, app2_.`name` as name3_0_2_, app2_.`reporter_username` as reporter4_0_2_, roles3_.`user_username` as user_use1_9_3_, roles3_.`roles` as roles2_9_3_ from `user` user0_ left outer join `user_permissions` permission1_ on user0_.`username`=permission1_.`user_username` left outer join `app` app2_ on permission1_.`app_id`=app2_.`id` left outer join `user_roles` roles3_ on user0_.`username`=roles3_.`user_username` where user0_.`username`=?
acrarium    | Hibernate: select count(distinct bug0_.`id`) as col_0_0_ from `bug` bug0_ left outer join `stacktrace` stacktrace1_ on (stacktrace1_.`bug_id`=bug0_.`id`) left outer join `report` report2_ on (report2_.`stacktrace_id`=stacktrace1_.`id`) left outer join `version` version3_ on bug0_.`solved_version`=version3_.`id` where bug0_.`app_id`=? and (bug0_.`solved_version` is null)
acrarium    | 2021-03-09 04:39:43.663 ERROR 1 --- [nio-8080-exec-4] c.v.flow.server.DefaultErrorHandler      :
acrarium    |
acrarium    | java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
acrarium    |   at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[na:na]
acrarium    |   at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[na:na]
acrarium    |   at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[na:na]
acrarium    |   at java.base/java.util.Objects.checkIndex(Unknown Source) ~[na:na]
acrarium    |   at java.base/java.util.ArrayList.get(Unknown Source) ~[na:na]
acrarium    |   at com.vaadin.flow.data.provider.DataCommunicator.lambda$getJsonItems$5(DataCommunicator.java:1297) ~[flow-data-5.0.2.jar:5.0.2]
acrarium    |   at java.base/java.util.stream.IntPipeline$1$1.accept(Unknown Source) ~[na:na]
acrarium    |   at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source) ~[na:na]
acrarium    |   at java.base/java.util.Spliterator$OfInt.forEachRemaining(Unknown Source) ~[na:na]
acrarium    |   at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
acrarium    |   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]
acrarium    |   at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[na:na]
acrarium    |   at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
acrarium    |   at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source) ~[na:na]
acrarium    |   at com.vaadin.flow.data.provider.DataCommunicator.getJsonItems(DataCommunicator.java:1299) ~[flow-data-5.0.2.jar:5.0.2]
acrarium    |   at com.vaadin.flow.data.provider.DataCommunicator.collectChangesToSend(DataCommunicator.java:1242) ~[flow-data-5.0.2.jar:5.0.2]
acrarium    |   at com.vaadin.flow.data.provider.DataCommunicator.flush(DataCommunicator.java:1128) ~[flow-data-5.0.2.jar:5.0.2]
acrarium    |   at com.vaadin.flow.data.provider.DataCommunicator.lambda$requestFlush$7258256f$1(DataCommunicator.java:1051) ~[flow-data-5.0.2.jar:5.0.2]
acrarium    |   at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$1(StateTree.java:368) ~[flow-server-5.0.2.jar:5.0.2]
acrarium    |   at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
acrarium    |   at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:365) ~[flow-server-5.0.2.jar:5.0.2]
acrarium    |   at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:389) ~[flow-server-5.0.2.jar:5.0.2]
acrarium    |   at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:172) ~[flow-server-5.0.2.jar:5.0.2]
acrarium    |   at com.vaadin.flow.server.communication.UidlRequestHandler.createUidl(UidlRequestHandler.java:158) ~[flow-server-5.0.2.jar:5.0.2]
acrarium    |   at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:146) ~[flow-server-5.0.2.jar:5.0.2]
acrarium    |   at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:115) ~[flow-server-5.0.2.jar:5.0.2]
acrarium    |   at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-5.0.2.jar:5.0.2]
acrarium    |   at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1539) ~[flow-server-5.0.2.jar:5.0.2]
acrarium    |   at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:238) ~[flow-server-5.0.2.jar:5.0.2]
acrarium    |   at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:110) ~[vaadin-spring-15.0.2.jar:na]
acrarium    |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) ~[spring-webmvc-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) ~[spring-webmvc-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52) ~[spring-webmvc-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1061) ~[spring-webmvc-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:961) ~[spring-webmvc-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.2.jar:5.3.2]
acrarium    |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:665) ~[javax.servlet-api-4.0.1.jar:4.0.1]
acrarium    |   at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.2.jar:5.3.2]
acrarium    |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:263) ~[ziplet-2.4.3.jar:na]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) ~[spring-security-web-5.4.2.jar:5.4.2]
acrarium    |   at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) ~[spring-web-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) ~[spring-web-5.3.2.jar:5.3.2]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar:5.3.2]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar:5.3.2]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) ~[spring-boot-actuator-2.4.1.jar:2.4.1]
acrarium    |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar:5.3.2]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar:5.3.2]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
acrarium    |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
acrarium    |   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
acrarium    |   at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
acrarium    |
```

**Comment by Kasina09** [comment]
Hello.
Is there a way to regain the inaccessible report?
Or how to delete the inaccessible app?

**Comment by F43nd1r** [comment]
I'm guessing there is some inconsistency in the database, some bugs linked to the nonexsistent version or something like that. If you can find that inconsistency you probably can fix it as well, but it requires manual work on the database.

**Comment by Kasina09** [comment]
Okay.
Btw I created New App and this version 0 appears again...

**Comment by F43nd1r** [comment]
This issue is on my radar. I'll investigate it eventually. Unfortunately I'm occupied otherwise right now.

**Comment by F43nd1r** [comment]
If possible please share the output of
```sql
SELECT * FROM report JOIN stacktrace ON report.stacktrace_id = stacktrace.id JOIN version ON stacktrace.version_id = version.id WHERE version.code = 0 
```

on both the broken and the new app with me.

**Comment by F43nd1r** [comment]
Also please let me know if you were using the latest version of acrarium when you deleted that version.

**Comment by Kasina09** [comment]
I used version 1.1.0 when I deleted.
Currently, there're only two apps in Acrarium: Acra-Testing (which version 0 I deleted) and Test (new app).

[log.txt](https://github.com/F43nd1r/Acrarium/files/6168293/log.txt)

**Comment by F43nd1r** [comment]
Okay, it seems your ACRA installation doesn't send `APP_VERSION_CODE`, which is why you'll see 0 for all versions.

**Comment by Kasina09** [comment]
Ah, I see. I just migrated from ACRA 4.9.2 to 5.7.0 and use the customReportContent in the newer version.
Is there a safe way to delete this version 0? It seems like when version 0 is deleted, the reports are also deleted but not the bug types. And that resulted in internal error.

**Comment by F43nd1r** [comment]
You should be able to correctly delete that version in the latest version. Make a backup of your database first just in case.
