### ISSUE TITLE
acra doesn't merge same bugs

### ISSUE THREAD

**Issue by mneckoee** [F43nd1r/Acrarium#41]
Hi. thank you for great effort.
version: 0.8.0
(screenshot)
![merging](https://user-images.githubusercontent.com/16606340/57060863-2d44ed00-6cd0-11e9-8ee2-83931152f7f6.png)
this bug :
`
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Paint.setColor(int)' on a null object reference
	at app.ui.Components.CheckBoxSquare.onDraw(CheckBoxSquare.java:132)
	at android.view.View.draw(View.java:16195)
	at android.view.View.updateDisplayListIfDirty(View.java:15192)
	at android.view.View.draw(View.java:15965)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16198)
	at android.view.View.updateDisplayListIfDirty(View.java:15192)
	at android.view.View.draw(View.java:15965)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15187)
	at android.view.View.draw(View.java:15965)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at app.ui.ActionBar.AlertDialog$2.drawChild(AlertDialog.java:348)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16198)
	at android.widget.ScrollView.draw(ScrollView.java:1712)
	at android.view.View.updateDisplayListIfDirty(View.java:15192)
	at android.view.View.draw(View.java:15965)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16198)
	at android.view.View.updateDisplayListIfDirty(View.java:15192)
	at android.view.View.draw(View.java:15965)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15187)
	at android.view.View.draw(View.java:15965)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15187)
	at android.view.View.draw(View.java:15965)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16198)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
	at android.view.View.updateDisplayListIfDirty(View.java:15192)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2620)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2439)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2072)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1112)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6035)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5484)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

and this bug: 
`
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Paint.setColor(int)' on a null object reference
	at app.ui.Components.CheckBoxSquare.onDraw(CheckBoxSquare.java:132)
	at android.view.View.draw(View.java:19187)
	at android.view.View.updateDisplayListIfDirty(View.java:18137)
	at android.view.View.draw(View.java:18915)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
	at android.view.View.draw(View.java:19190)
	at android.view.View.updateDisplayListIfDirty(View.java:18137)
	at android.view.View.draw(View.java:18915)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
	at android.view.View.updateDisplayListIfDirty(View.java:18128)
	at android.view.View.draw(View.java:18915)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
	at app.ui.ActionBar.AlertDialog$2.drawChild(AlertDialog.java:348)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
	at android.view.View.draw(View.java:19190)
	at android.widget.ScrollView.draw(ScrollView.java:1777)
	at android.view.View.updateDisplayListIfDirty(View.java:18137)
	at android.view.View.draw(View.java:18915)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
	at android.view.View.draw(View.java:19190)
	at android.view.View.updateDisplayListIfDirty(View.java:18137)
	at android.view.View.draw(View.java:18915)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
	at android.view.View.updateDisplayListIfDirty(View.java:18128)
	at android.view.View.draw(View.java:18915)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
	at android.view.View.updateDisplayListIfDirty(View.java:18128)
	at android.view.View.draw(View.java:18915)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
	at android.view.View.draw(View.java:19190)
	at com.android.internal.policy.DecorView.draw(DecorView.java:817)
	at android.view.View.updateDisplayListIfDirty(View.java:18137)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:643)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:649)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:757)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3080)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2884)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2437)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1441)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7171)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:726)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)`

their different is mostly in code lines.

**Comment by F43nd1r** [comment]
You can change the required matching percentage under admin -> configure bug matching.
Alternatively merge them manually.
