### ISSUE TITLE
Can't start Alpha 2 

### ISSUE THREAD

**Issue by federicoiosue** [F43nd1r/Acrarium#418]
Hi there, 

trying to give a look to the latest alpha 2 as outcome of [this considerations](https://github.com/F43nd1r/Acrarium/issues/416).
I tried both with binary took from Github and docker image but I'm always getting the following error at the very end:
```
2023-04-01T18:58:09.875+02:00 ERROR 33303 --- [           main] o.s.boot.SpringApplication               : Application run failed

com.univocity.parsers.common.DataProcessingException: Unable to instantiate class 'com.faendir.acra.setup.Device'
Internal state when error was thrown: line=2, column=0, record=1, charIndex=82, headers=[Retail Branding, Marketing Name, Device, Model], row=[null, null, AD681H, Smartfren Andromax AD681H]
	at com.univocity.parsers.common.processor.core.BeanConversionProcessor.createBean(BeanConversionProcessor.java:672) ~[univocity-parsers-2.9.1.jar!/:2.9.1]
	at com.univocity.parsers.common.processor.core.AbstractBeanProcessor.rowProcessed(AbstractBeanProcessor.java:54) ~[univocity-parsers-2.9.1.jar!/:2.9.1]
	at com.univocity.parsers.common.Internal.process(Internal.java:30) ~[univocity-parsers-2.9.1.jar!/:2.9.1]
	at com.univocity.parsers.common.AbstractParser.rowProcessed(AbstractParser.java:716) ~[univocity-parsers-2.9.1.jar!/:2.9.1]
	at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:152) ~[univocity-parsers-2.9.1.jar!/:2.9.1]
	at com.faendir.acra.setup.DeviceSetup.fillDeviceTable(DeviceSetup.kt:36) ~[classes!/:2.0.0-alpha01]
	at com.faendir.acra.setup.DeviceSetup.onStartup(DeviceSetup.kt:27) ~[classes!/:2.0.0-alpha01]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:343) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:228) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:165) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:937) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:587) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at com.faendir.acra.BackendApplicationKt.main(BackendApplication.kt:49) ~[classes!/:2.0.0-alpha01]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[acrarium-2.0.0-alpha01.jar:2.0.0-alpha01]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[acrarium-2.0.0-alpha01.jar:2.0.0-alpha01]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[acrarium-2.0.0-alpha01.jar:2.0.0-alpha01]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[acrarium-2.0.0-alpha01.jar:2.0.0-alpha01]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "this.constructor" is null
	at com.univocity.parsers.common.processor.core.BeanConversionProcessor.createBean(BeanConversionProcessor.java:670) ~[univocity-parsers-2.9.1.jar!/:2.9.1]
	... 35 common frames omitted

```

Here attached the docker-compose.yml I've used to get the result above. An important mention is that I had to enter into the databsse container and perform the following mysql command to get things working: `SET GLOBAL log_bin_trust_function_creators = 1`

[docker-compose.txt](https://github.com/F43nd1r/Acrarium/files/11130671/docker-compose.txt)

**Comment by F43nd1r** [comment]
> An important mention is that I had to enter into the databsse container and perform the following mysql command to get things working: SET GLOBAL log_bin_trust_function_creators = 1

You can start mysql with `--log-bin-trust-function-creators`. The requirement should probably be documented. I haven't started to update the wiki for v2.

---
Device setup is indeed broken. I hadn't noticed because I never started with a clean DB. Fix incoming.
