### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by assen-krastev** [F43nd1r/Acrarium#542]
I'm trying to build jar on macOS using openjdk-17.0.12 with:

./gradlew bootJar -x test -Pvaadin.productionMode=true

but I'm getting the following exception:

...
Exception in thread "main" java.lang.AbstractMethodError: Receiver class org.jooq.codegen.JavaGenerator$Resolver does not define or inherit an implementation of the resolved method 'abstract java.lang.Object resolveDefinedType(java.util.function.Supplier)' of interface org.jooq.meta.JavaTypeResolver.
        at org.jooq.meta.AbstractTypedElementDefinition.mapDefinedType(AbstractTypedElementDefinition.java:180)
        at org.jooq.meta.AbstractTypedElementDefinition.getType(AbstractTypedElementDefinition.java:145)
        at org.jooq.codegen.JavaGenerator.generateTable(JavaGenerator.java:6176)
        at org.jooq.codegen.JavaGenerator.generateTable(JavaGenerator.java:6055)
        at org.jooq.codegen.JavaGenerator.generateTables(JavaGenerator.java:6025)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:667)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:622)
        at org.jooq.codegen.JavaGenerator.generate0(JavaGenerator.java:534)
        at org.jooq.codegen.AbstractGenerator.generate(AbstractGenerator.java:191)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:222)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:944)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:244)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:239)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:211)

> Task :acrarium:generateJooq FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':acrarium:generateJooq'.
> Process 'command '/opt/homebrew/Cellar/openjdk@17/17.0.12/libexec/openjdk.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 18s
24 actionable tasks: 21 executed, 3 up-to-date

Are there any prerequisites I am missing?

**Comment by F43nd1r** [comment]
Fixed the master build as well now.
