### ISSUE TITLE
Exception when merging Bugs

### ISSUE THREAD

**Issue by xxxEWxxx** [F43nd1r/Acrarium#6]
Hibernate: select vbug0_.id as id1_5_, vbug0_.app_id as app_id7_5_, vbug0_.solved as solved2_5_, vbug0_.title as title3_5_, vbug0_.version_code as version_4_5_, vbug0_.last_report as last_rep5_5_, vbug0_.report_count as report_c6_5_ from bug_view vbug0_ where vbug0_.app_id=? and vbug0_.solved=0 order by vbug0_.last_report desc limit ?
Hibernate: select bug0_.id as id1_3_0_, bug0_.app_id as app_id5_3_0_, bug0_.solved as solved2_3_0_, bug0_.title as title3_3_0_, bug0_.version_code as version_4_3_0_ from bug bug0_ where bug0_.id=?
2018-06-13 14:42:09.428 ERROR 34853 --- [nio-8080-exec-3] com.vaadin.server.DefaultErrorHandler    : 

org.springframework.dao.InvalidDataAccessApiUsageException: Parameter value element [com.faendir.acra.model.view.VBug@3] did not match expected type [com.faendir.acra.model.Bug (n/a)]; nested exception is java.lang.IllegalArgumentException: Parameter value element [com.faendir.acra.model.view.VBug@3] did not match expected type [com.faendir.acra.model.Bug (n/a)]
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:367) ~[spring-orm-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:227) ~[spring-orm-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:527) ~[spring-orm-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61) ~[spring-tx-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242) ~[spring-tx-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153) ~[spring-tx-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135) ~[spring-data-jpa-2.0.7.RELEASE.jar:2.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.0.7.RELEASE.jar:2.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at com.sun.proxy.$Proxy137.loadStacktraces(Unknown Source) ~[na:na]
	at com.faendir.acra.service.data.DataService.mergeBugs(DataService.java:159) ~[classes/:na]
	at com.faendir.acra.service.data.DataService$$FastClassBySpringCGLIB$$b263246b.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at com.faendir.acra.service.data.DataService$$EnhancerBySpringCGLIB$$13a7f921.mergeBugs(<generated>) ~[classes/:na]
	at com.faendir.acra.ui.view.app.tabs.BugTab.lambda$createContent$1(BugTab.java:77) ~[classes/:na]
	at com.faendir.acra.ui.view.base.Popup.lambda$addCreateButton$a7fdd7ae$1(Popup.java:48) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499) ~[vaadin-server-8.4.2.jar:8.4.2]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273) ~[vaadin-server-8.4.2.jar:8.4.2]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237) ~[vaadin-server-8.4.2.jar:8.4.2]
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1014) ~[vaadin-server-8.4.2.jar:8.4.2]
	at com.vaadin.ui.Button.fireClick(Button.java:384) ~[vaadin-server-8.4.2.jar:8.4.2]
	at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-8.4.2.jar:8.4.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155) ~[vaadin-server-8.4.2.jar:8.4.2]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116) ~[vaadin-server-8.4.2.jar:8.4.2]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445) [vaadin-server-8.4.2.jar:8.4.2]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410) [vaadin-server-8.4.2.jar:8.4.2]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274) [vaadin-server-8.4.2.jar:8.4.2]
	at com.vaadin.server.communication.PushHandler.lambda$new$1(PushHandler.java:146) [vaadin-server-8.4.2.jar:8.4.2]
	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:236) [vaadin-server-8.4.2.jar:8.4.2]
	at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:522) [vaadin-server-8.4.2.jar:8.4.2]
	at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:87) ~[vaadin-server-8.4.2.jar:8.4.2]
	at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77) ~[vaadin-server-8.4.2.jar:8.4.2]
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:224) ~[atmosphere-runtime-2.4.24.vaadin1.jar:2.4.24.vaadin1]
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:114) ~[atmosphere-runtime-2.4.24.vaadin1.jar:2.4.24.vaadin1]
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67) ~[atmosphere-runtime-2.4.24.vaadin1.jar:2.4.24.vaadin1]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2290) ~[atmosphere-runtime-2.4.24.vaadin1.jar:2.4.24.vaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:594) ~[atmosphere-runtime-2.4.24.vaadin1.jar:2.4.24.vaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:345) ~[atmosphere-runtime-2.4.24.vaadin1.jar:2.4.24.vaadin1]
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101) ~[atmosphere-runtime-2.4.24.vaadin1.jar:2.4.24.vaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:340) ~[atmosphere-runtime-2.4.24.vaadin1.jar:2.4.24.vaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:448) ~[atmosphere-runtime-2.4.24.vaadin1.jar:2.4.24.vaadin1]
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:272) ~[atmosphere-runtime-2.4.24.vaadin1.jar:2.4.24.vaadin1]
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:269) ~[atmosphere-runtime-2.4.24.vaadin1.jar:2.4.24.vaadin1]
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:399) ~[tomcat-websocket.jar:8.5.6]
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:106) ~[tomcat-websocket.jar:8.5.6]
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:500) ~[tomcat-websocket.jar:8.5.6]
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:295) ~[tomcat-websocket.jar:8.5.6]
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:131) ~[tomcat-websocket.jar:8.5.6]
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:69) ~[tomcat-websocket.jar:8.5.6]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148) ~[tomcat-websocket.jar:8.5.6]
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54) ~[tomcat-coyote.jar:8.5.6]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53) ~[tomcat-coyote.jar:8.5.6]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) ~[tomcat-coyote.jar:8.5.6]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) ~[tomcat-coyote.jar:8.5.6]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.6]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]

**Comment by xxxEWxxx** [comment]
Hello,
this is the full stacktrace from Tomcat startup till exception 
[catalina.out.txt](https://github.com/F43nd1r/Acrarium/files/2102743/catalina.out.txt)

**Comment by F43nd1r** [comment]
Which version are you running? The line numbers do not match 0.4.1

**Comment by xxxEWxxx** [comment]
Sorry, my fault. I was running 0.4.0. Issue does not occure in 0.4.1
