### ISSUE TITLE
There is a bug here

### ISSUE THREAD

**Issue by xuelu123** [F43nd1r/Acrarium#80]
When I opened the Statistics(version is v0.10.7), the chart was not drawn,the log is as follows:

java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.sql.Date cannot be cast to java.time.ZonedDateTime
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_251]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_251]
	at com.vaadin.flow.server.FutureAccess.get(FutureAccess.java:62) ~[flow-server-3.2.0.alpha3.jar:3.2.0.alpha3]
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2024) [flow-server-3.2.0.alpha3.jar:3.2.0.alpha3]
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:668) [flow-server-3.2.0.alpha3.jar:3.2.0.alpha3]
	at com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1987) [flow-server-3.2.0.alpha3.jar:3.2.0.alpha3]
	at com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:1954) [flow-server-3.2.0.alpha3.jar:3.2.0.alpha3]
	at com.vaadin.flow.server.VaadinSession.access(VaadinSession.java:956) [flow-server-3.2.0.alpha3.jar:3.2.0.alpha3]
	at com.vaadin.flow.component.UI.access(UI.java:507) [flow-server-3.2.0.alpha3.jar:3.2.0.alpha3]
	at com.vaadin.flow.component.UI.access(UI.java:490) [flow-server-3.2.0.alpha3.jar:3.2.0.alpha3]
	at com.faendir.acra.ui.component.statistics.Statistics$3$1.accept(Statistics.kt:67) [classes/:0.10.7]
	at com.faendir.acra.ui.component.statistics.Statistics$3$1.accept(Statistics.kt:40) [classes/:0.10.7]
	at java.util.Optional.ifPresent(Optional.java:159) [na:1.8.0_251]
	at com.faendir.acra.ui.component.statistics.Statistics$3.invokeSuspend(Statistics.kt:67) [classes/:0.10.7]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) [kotlinx-coroutines-core-1.3.6.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-1.3.6.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) [kotlinx-coroutines-core-1.3.6.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-1.3.6.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-1.3.6.jar:na]
Caused by: java.lang.ClassCastException: java.sql.Date cannot be cast to java.time.ZonedDateTime
	at com.faendir.acra.ui.component.statistics.TimeChart$createChart$list$2.invoke(TimeChart.kt:39) ~[classes/:0.10.7]
	at com.faendir.acra.ui.component.statistics.TimeChart$createChart$list$2.invoke(TimeChart.kt:37) ~[classes/:0.10.7]
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172) ~[kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:722) ~[kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:752) ~[kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:743) ~[kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
	at com.faendir.acra.ui.component.statistics.TimeChart.createChart(TimeChart.kt:39) ~[classes/:0.10.7]
	at com.faendir.acra.ui.component.statistics.Chart.setContent(Chart.kt:40) ~[classes/:0.10.7]
	at com.faendir.acra.ui.component.statistics.Property.update(Property.kt:70) ~[classes/:0.10.7]
	at com.faendir.acra.ui.component.statistics.Statistics.update(Statistics.kt:73) ~[classes/:0.10.7]
	at com.faendir.acra.ui.component.statistics.Statistics.access$update(Statistics.kt:40) ~[classes/:0.10.7]
	at com.faendir.acra.ui.component.statistics.Statistics$3$1$1.execute(Statistics.kt:67) ~[classes/:0.10.7]
	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:435) [flow-server-3.2.0.alpha3.jar:3.2.0.alpha3]
	at com.vaadin.flow.component.UI.access$000(UI.java:94) [flow-server-3.2.0.alpha3.jar:3.2.0.alpha3]
	at com.vaadin.flow.component.UI$2.execute(UI.java:510) ~[flow-server-3.2.0.alpha3.jar:3.2.0.alpha3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_251]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_251]
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2021) [flow-server-3.2.0.alpha3.jar:3.2.0.alpha3]
	... 16 common frames omitted

**Comment by F43nd1r** [comment]
Fixed in v0.10.9
